In [4]:
import numpy as np

In [5]:
A = np.array( [ 
[52, 55, 61, 59], 
[49, 50, 60, 58], 
[48, 52, 62, 60], 
[47, 49, 59, 57] 
])

print(A)

[[52 55 61 59]
 [49 50 60 58]
 [48 52 62 60]
 [47 49 59 57]]


In [6]:
#Transpose
transpose = np.array(A.T)

print(transpose)

[[52 49 48 47]
 [55 50 52 49]
 [61 60 62 59]
 [59 58 60 57]]


In [7]:
#Determinant
determinant = np.linalg.det(A)

print(determinant)

40.00000000000051


In [8]:
#Rank
rank = np.linalg.matrix_rank(A)

print(rank)

4


In [9]:
#Singular Value Decomposition
U, S, Vt = np.linalg.svd(A)
print(U,"\n", S,"\n", Vt)

print()

#Extract singular values
singular_values = np.linalg.svd(A)
print("Singular Values\n", singular_values)


[[-0.51578198 -0.82961673  0.20734409  0.05209091]
 [-0.49421532  0.10212857 -0.69061026 -0.51805254]
 [-0.50624167  0.460644    0.66104796 -0.30747693]
 [-0.48315581  0.29851791 -0.20756078  0.79647099]] 
 [2.20391444e+02 3.64333188e+00 1.52854497e+00 3.25902960e-02] 
 [[-0.44486816 -0.46770408 -0.54906304 -0.53091901]
 [-0.54744276 -0.53292576  0.46484349  0.44745624]
 [-0.70855922  0.70487142 -0.03253984  0.006424  ]
 [-0.01850883  0.01998267  0.6938238  -0.71962952]]

Singular Values
 SVDResult(U=array([[-0.51578198, -0.82961673,  0.20734409,  0.05209091],
       [-0.49421532,  0.10212857, -0.69061026, -0.51805254],
       [-0.50624167,  0.460644  ,  0.66104796, -0.30747693],
       [-0.48315581,  0.29851791, -0.20756078,  0.79647099]]), S=array([2.20391444e+02, 3.64333188e+00, 1.52854497e+00, 3.25902960e-02]), Vh=array([[-0.44486816, -0.46770408, -0.54906304, -0.53091901],
       [-0.54744276, -0.53292576,  0.46484349,  0.44745624],
       [-0.70855922,  0.70487142, -0.03253984,  

In [29]:
U, S, V = np.linalg.svd(A)
singular_values = np.linalg.svd(A)[1]
print(singular_values)

print()
top_k_singular_values = singular_values[:k]
reconstructed_matrix = U @ S, V @ V
print(reconstructed_matrix)

[2.20391444e+02 3.64333188e+00 1.52854497e+00 3.25902960e-02]

(array([-116.37787219, -109.6212527 , -108.89263297, -105.68711514]), array([[ 0.85281926,  0.05969018, -0.32364635,  0.40544967],
       [ 0.19763517,  0.87664734,  0.34818337, -0.26682976],
       [-0.04772382, -0.06705614,  0.72221454,  0.68675474],
       [-0.48100113,  0.47268382, -0.50242168,  0.54109184]]))


In [30]:
mse = np.mean((A - reconstructed_matrix)**2)
original_matrix = np.array([[52, 55, 61, 59],
                            [49, 50, 60, 58],
                            [48, 52, 62, 60],
                            [47, 49, 59, 57]])
compressed_matrix = U @ S, V @ V

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 4) + inhomogeneous part.