**Data Science Libraries**
1. NumPy: Numerical Python
    - numerical computation
    - matrix calculation with arrays
    - statics
    - linear algebra
    - random sampling
    - data processing for ML
    

In [1]:
import numpy as np
arr = np.array([101,20,30,40])

In [2]:
print(arr)
print(type(arr))

[101  20  30  40]
<class 'numpy.ndarray'>


In [3]:
#create evenly spaced values within the range

arr = np.arange(0,45,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [4]:
#np.linspace() : create equally space value

arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#Create the array filled with ones

arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#Create an array with  specific value
arr = np.full((2,3),7)
arr

array([[7, 7, 7],
       [7, 7, 7]])

In [8]:
# Creates an identity matrix: Linear algebra
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Create an array with random values between 0 and 1

arr = np.random.randint(5)

arr = np.random.rand(5)
arr

array([0.50043569, 0.53035885, 0.63175832, 0.91245865, 0.59502709])

**Attributes:**
- ndim : return number of dimension in array
- shape : returns rows and column as a tuple
- size : returns total number of elements in array
- dtype : returns data type of elements

In [10]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [11]:
arr = np.full((2,3),5)
arr
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


2
(2, 3)
6
int64


In [12]:
arr = np.arange(1, 21)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:

arr = np.linspace(2, 5, 10)
arr

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [14]:
#Flatterns a multi dimensional array into 1D array
arr = np.array([[1,2],[3,4]])
arr1 = arr.ravel()
arr1

array([1, 2, 3, 4])

In [15]:
#Converts array into 1D, often returns the copy

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
flat = arr.flatten()
flat

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#Transpose: rows and columns are interchanged
arr = np.array([[1,2,1],[1,3,4]])
print(arr)
print("---------")
print(arr.T)


[[1 2 1]
 [1 3 4]]
---------
[[1 1]
 [2 3]
 [1 4]]


In [17]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[:])
print(arr[2:4])


10
50
[10 20 30 40 50]
[30 40]


In [18]:
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [19]:
print(arr[0,1])
print("---------")
print(arr[:1])
print("---------")
print(arr[:,1])
print("---------")
print(arr[:,-1])
print("---------")
print(arr[1:,1:])

2
---------
[[1 2 3]]
---------
[2 4 6]
---------
[3 5 7]
---------
[[4 5]
 [6 7]]


In [20]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
             
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [22]:
arr = np.array([1,2,3])
print(arr + 10)



[11 12 13]


In [23]:
a = np.array([[1], [2], [3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


*Aggregation Methods:*
1. sum()
2. max()
3. min()
4. mean()
5. median()
6. std()


In [24]:
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

150
50
10
30.0
30.0
14.142135623730951


In [25]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
print(np.sum(arr, axis=0)) #column wise sum
print(np.sum(arr, axis=1)) #row wise sum
print(np.sum(arr))

print(arr.sum(0)) #column wise sum

[[1 2 3]
 [4 5 6]]

[5 7 9]
[ 6 15]
21
[5 7 9]


*Universal Functions*
1.log
2.sqrt
3.exp
4.sin

In [26]:
arr = np.array([1,4,9,16,25])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.sin(arr))

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [27]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))
print(np.cos(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [28]:
arr = np.array([10,15,20,25,30,35])

mask = arr > 20
print(mask)
print(arr[mask])

[False False False  True  True  True]
[25 30 35]


In [29]:
#Filtering

arr = np.array([10,15,20,25,30,35])

res = arr[(arr > 10) & (arr % 2 == 0)]
print(res)

[20 30]


In [30]:
arr = np.array([1,34,67,23,89,2,48])
print(np.sort(arr))

print(np.argsort(arr))
print(np.argsort(arr[::-1]))


[ 1  2 23 34 48 67 89]
[0 5 3 1 6 2 4]
[6 1 3 5 0 4 2]


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])