# Python Exception Handling & File Handling
## Complete Guide with Demos and NumPy Introduction

## Part 1: Exception Handling in Python

### Demo 5: Basic Exception Handling

In [19]:
#Exception Demo 5
n = 10
try:
    print("start............")
    res = n / 0
    print("try..............")
except ZeroDivisionError:
    print("Can't divide by zero")
    print("except...........")
    
print("end.............")

start............
Can't divide by zero
except...........
end.............


### Demo 6: Multiple Exception Handling

In [20]:
#Exception Demo 6
try:
    print("start............")
    num = int(input("Enter index: "))
    lst = [1, 2, 3, 4, 5]
    print(lst[num])
    print("try..............")
except ValueError:
    print("Enter Number")
    print("except.......1")
except IndexError:
    print("Enter valid index")
    print("except.......2")
    
print("end.............")

start............
4
try..............
end.............


### Demo 8: Handling Multiple Exceptions in One Block

In [21]:
#Exception Demo 8
try:
    print("start............")
    num = int(input("Enter index: "))
    lst = [1, 2, 3, 4, 5]
    print(lst[num])
    print("try..............")
except (ValueError, IndexError):
    print("Enter Number or valid index")
    print("except.......1 and 2")
    
print("end.............")

start............
5
try..............
end.............


### Demo 9: Generic Exception Handling

In [22]:
#Exception Demo 9
try:
    print("start............")
    num = int(input("Enter index: "))
    lst = [1, 2, 3, 4, 5]
    print(lst[num])
    print("try..............")
except Exception as e:
    print("Something wrong!!!", e)
    print("except.......1 and 2")
    
print("end.............")

start............
5
try..............
end.............


### Demo 10: try-except-else-finally

In [23]:
#Exception Demo 10
try:
    n = 100 / 0
    print("try")
except Exception as e:
    print("except", e)
else:
    print("else")
finally:
    print("finally")

except division by zero
finally


### Demo 11: try-finally (No except)

In [24]:
#Exception Demo 11
try: 
    n = 100 / 10
    print("try")
finally:
    print("finally")

try
finally


### Demo 12: try-except-finally

In [25]:
#Exception Demo 12
try: 
    n = 100 / 10
    print("try")
except Exception as e:
    print("except", e)
finally:
    print("finally")

try
finally


### Demo 13: Nested try-except

In [26]:
#Exception Demo 13
try:
    num = int(input("Enter number:"))
    try:
        print(100 / num)
    except ZeroDivisionError:
        print("Division error")
        print("except : Inner")
    print("try : Inner")
    print("try : Outer")
except Exception as e:
    print("except", e)
    print("except : Outer")
else:
    print("else")
finally:
    print("finally")

1.8867924528301887
try : Inner
try : Outer
else
finally


### Demo 14: Raising Exceptions (raise)

In [27]:
#Exception Demo 14
# Raise - it is used to throw an exception manually.
age = -11
try:
    if age < 0:
        raise ValueError("Age can't be negative")
except ValueError as e:
    print("Error:", e)

Error: Age can't be negative


### Demo 15: TypeError Handling

In [28]:
#Exception Demo 15
try:
    res = "10" + 5
    print(res)
except TypeError as e:
    print("Type Error:", e)
except Exception as e:
    print("Error:", e)

Type Error: can only concatenate str (not "int") to str


### Demo 16: Exception Chaining

In [29]:
#Exception Demo 16
try:
    x = int("abc")
    print(x)
except ValueError as e:
    raise TypeError("An error occurred") from e

TypeError: An error occurred

### Exception Chaining Explanation

**Exception Chaining:**
- When one exception is raised while handling another exception.
- It helps to preserve the original error context.
- It can be implemented using: `raise..... from.....`
- It shows the root cause of the error.
- It improves debugging clarity.

Syntax:
```python
raise NewException("message") from OriginalException
```

### Demo 17: Exception Chaining Example

In [ ]:
#Exception Demo 17 (with chaining)
def divide(a, b):
    try:
        return a/b
    except ZeroDivisionError as e:
        raise ValueError("Cannot divide by zero") from e
    
try:
    divide(10, 0)
except ValueError as e:
    print("Caught:", e)
    print("Original exception:", e.__cause__)

### Demo 17 (without chaining)

In [ ]:
#Exception Demo 17 (without chaining)
def divide(a, b):
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b
    
try:
    divide(10, 0)
except ValueError as e:
    print(e)

### Demo 18: Custom Exception

In [ ]:
#Exception Demo 18
class InsufficientBalanceError(Exception):
    pass

def withdraw(balance, amount):
    if amount > balance:
        raise InsufficientBalanceError("Not sufficient balance.......")
    return balance - amount

try:
    balance = withdraw(10000, 15000)
    print("Withdrawal successful. New balance:", balance)
except InsufficientBalanceError as e:
    print("Custom Exception is defined..........", e)

## Part 2: File Handling in Python

**File Handling:**
- Process of creating, opening, reading, writing and closing files.
- Purpose: store data permanently (RAM → Disk).
- Used for: student data, employee records, logs, reports, config files.
- File types: txt, csv, json, sql, etc.

### File Modes

Opening a file: `file_object = open("fileName", "mode")`

**Basic Modes:**
- **r**: Read (file must exist, default mode)
- **w**: Write (creates/overwrites file)
- **a**: Append (creates/append to file)
- **x**: Exclusive create (error if exists)
- **b**: Binary mode (rb, wb, ab for images, PDFs)

**Combined Modes:**
- **r+**: Read and write (file must exist)
- **w+**: Read and write (overwrites/creates)
- **a+**: Read and append (creates/appends)

### READ DEMO

In [ ]:
# Create a file first for reading
with open("abc.txt", "w") as f:
    f.write("This is a sample text file.\nIt contains multiple lines.\nFor testing purposes.")

# READ DEMO
f = open("abc.txt", "r")
print(f.read())
f.close()

### WRITE DEMO

In [ ]:
#WRITE DEMO
f = open("abc.txt", "w")
print("Characters written:", f.write("Hello CDAC, Hello World !!!!!"))
f.close()

# Verify the write operation
f = open("abc.txt", "r")
print("File content after write:", f.read())
f.close()

### APPEND DEMO

In [ ]:
#APPEND DEMO
f = open("abc.txt", "a")
print("Characters appended:", f.write("Welcome to CDAC, Welcome to Python Programming"))
f.close()

# Verify the append operation
f = open("abc.txt", "r")
print("File content after append:", f.read())
f.close()

### EXCLUSIVE CREATE MODE DEMO

In [ ]:
#EXCLUSIVE CREATE MODE DEMO
try:
    f = open("abcd.txt", "x")
    f.write("Implementation is important to understand the programming")
    f.close()
    print("File created successfully")
except FileExistsError:
    print("File already exists")

# Read the created file
try:
    f = open("abcd.txt", "r")
    data = f.read()
    print("File content:", data)
    f.close()
except FileNotFoundError:
    print("File not found")

### Multiple File Operations Demo

In [ ]:
# Multiple file operations
# Write to Demo.txt
f = open("Demo.txt", "w")
f.write("This is a demo file for file handling in Python")
f.close()

# Append to Demo.txt
f = open("Demo.txt", "a")
f.write("\nThis is a demo file for file handling in Python 90")
f.close()

# Read Demo.txt
f = open("Demo.txt", "r")
print(f.read())
f.close()

### readline() Demo

In [ ]:
# Create a file with multiple lines
with open("Demo1.txt", "w") as f:
    f.write("Line 1: Python Programming\nLine 2: File Handling\nLine 3: Exception Handling")

# Reading with readline()
f = open("Demo1.txt", "r")
print("Using readline():")
data1 = f.readline()
data2 = f.readline()
data3 = f.readline()
print(data1, end="")
print(data2, end="")
print(data3)
f.close()

### write() with multiple writes

In [ ]:
# write() with multiple writes
f = open("abcde.txt", "w")
data = f.write("Learn Python: with file handling")
print("Characters =", data)
f.write("Learn Python: 1")
f.write("Learn Python: 2")
f.write("Learn Python: 3")
f.close()

# Read and display
f = open("abcde.txt", "r")
print("File content:", f.read())
f.close()

### writelines() Demo

In [ ]:
# writelines() Demo
lines = ["Ankit\n", "Basant\n", "Ravi\n"]
f = open("abcde.txt", "w")
f.writelines(lines)
f.close()

# Read and display
f = open("abcde.txt", "r")
print("File content using writelines:")
print(f.read())
f.close()

### File Pointer: tell() and seek()

In [ ]:
# File pointer operations
import os

# Create a file with content
with open("abcde.txt", "w") as f:
    f.write("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")

with open("abcde.txt", "r") as f:
    print("tell() - starting position =", f.tell())
    print(f.read(5))
    print("tell() - after reading 5 chars =", f.tell())
    f.seek(0)
    print("After seek(0):", f.read())

    # File properties
    if os.path.exists("abcde.txt"):
        print("File exists")
    else:
        print("File does not exist")
    print("File name:", f.name)
    print("File mode:", f.mode)
    print("File closed?:", f.closed)

### Exception Handling with Files

In [ ]:
#Exception handling with file handling
try:
    with open("abc90.txt", "r") as f:
        print(f.read())
except FileNotFoundError:
    print("File not found!")

## Part 3: NumPy - Numerical Python

**NumPy Features:**
- Numerical computation
- Matrix calculations with arrays
- Statistics
- Linear algebra
- Random sampling
- Data processing for ML

In [ ]:
# Import NumPy
import numpy as np

# Creating basic arrays
arr = np.array([101,20,30,40])
print(arr)
print(type(arr))

[101  20  30  40]
<class 'numpy.ndarray'>


### Array Creation Methods

In [ ]:
# np.arange()
arr = np.arange(0,45,3)
print("arange(0,45,3):", arr)

arange(0,45,3): [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42]


In [30]:
# np.linspace()
arr = np.linspace(0,1,10)
print("linspace(0,1,10):", arr)

linspace(0,1,10): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [31]:
# np.zeros()
arr = np.zeros((2,3))
print("zeros((2,3)):\n", arr)

zeros((2,3)):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# np.ones()
arr = np.ones((3,4))
print("ones((3,4)):\n", arr)

ones((3,4)):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
# np.full()
arr = np.full((2,3),7)
print("full((2,3),7):\n", arr)

full((2,3),7):
 [[7 7 7]
 [7 7 7]]


In [34]:
# np.eye() - identity matrix
arr = np.eye(3)
print("eye(3):\n", arr)

eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# Random arrays
arr = np.random.randint(0, 10, 5)
print("random.randint(0,10,5):", arr)

arr = np.random.rand(5)
print("random.rand(5):", arr)

random.randint(0,10,5): [7 5 5 1 3]
random.rand(5): [0.22441226 0.40674228 0.07531773 0.3764059  0.80428948]


### Array Attributes

In [36]:
# Array attributes
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int32


In [37]:
# More examples
arr = np.full((2,3),5)
print("Array:\n", arr)
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

arr = np.arange(1, 21)
print("\narange(1,21):", arr)

arr = np.linspace(2, 5, 10)
print("linspace(2,5,10):", arr)

Array:
 [[5 5 5]
 [5 5 5]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int32

arange(1,21): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
linspace(2,5,10): [2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


### Array Manipulation

In [38]:
# ravel() - flatten to 1D
arr = np.array([[1,2],[3,4]])
arr1 = arr.ravel()
print("Original:\n", arr)
print("ravel():", arr1)

Original:
 [[1 2]
 [3 4]]
ravel(): [1 2 3 4]


In [39]:
# flatten() - returns copy
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original:\n", arr)
flat = arr.flatten()
print("flatten():", flat)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
flatten(): [1 2 3 4 5 6 7 8 9]


In [40]:
# transpose()
arr = np.array([[1,2,1],[1,3,4]])
print("Original:\n", arr)
print("Transpose (arr.T):\n", arr.T)

Original:
 [[1 2 1]
 [1 3 4]]
Transpose (arr.T):
 [[1 1]
 [2 3]
 [1 4]]


### Indexing and Slicing

In [41]:
# 1D indexing
arr = np.array([10,20,30,40,50])
print("Array:", arr)
print("arr[0]:", arr[0])
print("arr[-1]:", arr[-1])
print("arr[:]:", arr[:])
print("arr[2:4]:", arr[2:4])

Array: [10 20 30 40 50]
arr[0]: 10
arr[-1]: 50
arr[:]: [10 20 30 40 50]
arr[2:4]: [30 40]


In [42]:
# 2D indexing
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
print("Array:\n", arr)
print("arr[0,1]:", arr[0,1])
print("arr[:1]:\n", arr[:1])
print("arr[:,1]:", arr[:,1])
print("arr[:,-1]:", arr[:,-1])
print("arr[1:,1:]:\n", arr[1:,1:])

Array:
 [[1 2 3]
 [3 4 5]
 [5 6 7]]
arr[0,1]: 2
arr[:1]:
 [[1 2 3]]
arr[:,1]: [2 4 6]
arr[:,-1]: [3 5 7]
arr[1:,1:]:
 [[4 5]
 [6 7]]


In [43]:
# Another example
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print("Array:\n", arr)

Array:
 [[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


### Array Operations

In [44]:
# Basic arithmetic
a = np.array([1,2,3])
b = np.array([4,5,6])
             
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]


In [45]:
# Broadcasting
arr = np.array([1,2,3])
print("arr + 10 =", arr + 10)

a = np.array([[1], [2], [3]])
b = np.array([10,20,30])
print("\na + b with broadcasting:\n", a + b)

arr + 10 = [11 12 13]

a + b with broadcasting:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### Aggregation Methods

In [46]:
arr = np.array([10,20,30,40,50])
print("Array:", arr)
print("sum:", np.sum(arr))
print("max:", np.max(arr))
print("min:", np.min(arr))
print("mean:", np.mean(arr))
print("median:", np.median(arr))
print("std:", np.std(arr))

Array: [10 20 30 40 50]
sum: 150
max: 50
min: 10
mean: 30.0
median: 30.0
std: 14.142135623730951


In [47]:
# Aggregation with axis
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("\nSum (axis=0, column-wise):", np.sum(arr, axis=0))
print("Sum (axis=1, row-wise):", np.sum(arr, axis=1))
print("Total sum:", np.sum(arr))

Array:
 [[1 2 3]
 [4 5 6]]

Sum (axis=0, column-wise): [5 7 9]
Sum (axis=1, row-wise): [ 6 15]
Total sum: 21


### Universal Functions (ufunc)

In [48]:
arr = np.array([1,4,9,16,25])
print("Array:", arr)
print("sqrt:", np.sqrt(arr))
print("log:", np.log(arr))
print("exp:", np.exp(arr))
print("sin:", np.sin(arr))

Array: [ 1  4  9 16 25]
sqrt: [1. 2. 3. 4. 5.]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [49]:
# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print("Angles:", angles)
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))

Angles: [0.         1.57079633 3.14159265]
sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


### Boolean Masking and Filtering

In [50]:
arr = np.array([10,15,20,25,30,35])
mask = arr > 20
print("Array:", arr)
print("Mask (arr > 20):", mask)
print("Filtered:", arr[mask])

Array: [10 15 20 25 30 35]
Mask (arr > 20): [False False False  True  True  True]
Filtered: [25 30 35]


In [51]:
# Complex filtering
arr = np.array([10,15,20,25,30,35])
res = arr[(arr > 10) & (arr % 2 == 0)]
print("Array:", arr)
print("Elements >10 and even:", res)

Array: [10 15 20 25 30 35]
Elements >10 and even: [20 30]


### Sorting

In [52]:
arr = np.array([1,34,67,23,89,2,48])
print("Original:", arr)
print("Sorted:", np.sort(arr))
print("Argsort (indices):", np.argsort(arr))

Original: [ 1 34 67 23 89  2 48]
Sorted: [ 1  2 23 34 48 67 89]
Argsort (indices): [0 5 3 1 6 2 4]


### Concatenation

In [53]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a:", a)
print("b:", b)
print("concatenate:", np.concatenate((a,b)))

a: [1 2 3]
b: [4 5 6]
concatenate: [1 2 3 4 5 6]


In [54]:
# vstack and hstack
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print("vstack:\n", np.vstack((a,b)))
print("\nhstack:", np.hstack((a,b)))

vstack:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

hstack: [ 1  2  3  4  5  6  7  8  9 10]
